### ISSUE TITLE
Environment build: MacOS won't take localhost

### ISSUE THREAD

**Issue by SecondeJK** [sulu/sulu-standard#722] opened 2016-07-14 10:05 UTC
| Q | A
| --- | ---
| Bug? | No
| New Feature? | No
| Sulu Version | master
| Browser Version | CLI

#### Actual Behavior
app/console sulu:build prod won't recognise the mysql connection if the dbhost is set to localhost, but does if it's set to 127.0.0.1

#### Expected Behavior

config.yml can use either localhost or 127 disregarding environment

#### Steps to Reproduce

MacOS El Capitaine
git clone [master]
composer install
input localhost as host at CLI prompt
attempt app/console sulu:build prod

**Comment by wachterjohannes** [comment] 2016-07-25 06:54
@SecondeJK is that really a sulu problem? without testing it i would think that this also wont work for other symfony (or doctrine) projects. Do you have tested this? /cc @danrot what do you think?

**Comment by SecondeJK** [comment] 2016-07-25 07:28
@wachterjohannes if it's doctrine or symfony then I guess close...not sure when I'd able to test it. I do have another project using symfony core so if this comes up I'll look

**Comment by wachterjohannes** [comment] 2016-07-25 07:29
thanks maybe i also have time to install symfony demo and test it.

**Comment by danrot** [comment] 2016-07-25 13:28
Since we do not modify anything when registering the database settings I would say this issue doesn't belong to us. I'd say we close it for now, and you can reopen it, in case you find out that the issue is really in Sulu.

**Closed by danrot** 2016-07-25 13:28 UTC
