### ISSUE TITLE
Symfony 2.8.10

### ISSUE THREAD

**Issue by Reyh** [sulu/sulu-standard#744] opened 2016-09-05 15:07 UTC
After updating from symfony 2.8.9 to 2.8.10 I experience the following exception for any request. : 
_You have requested a synthetic service ("request"). The DIC does not know how to construct this service._

RuntimeException in appDevDebugProjectContainer.php line 7425:
You have requested a synthetic service ("request"). The DIC does not know how to construct this service.
in appDevDebugProjectContainer.php line 7425
at appDevDebugProjectContainer->getRequestService() in bootstrap.php.cache line 2221
at Container->get('request', '2') in appDevDebugProjectContainer.php line 10835
at appDevDebugProjectContainer->synchronizeRequestService() in bootstrap.php.cache line 2157
at Container->set('request', null, 'request') in bootstrap.php.cache line 3360
at ContainerAwareHttpKernel->handle(object(Request), '1', true) in bootstrap.php.cache line 2535
at Kernel->handle(object(Request)) in app_dev.php line 28

Thanks

**Comment by alexander-schranz** [comment] 2016-09-05 15:44
not sure if this is a symfony problem: https://github.com/symfony/symfony/issues/19840 @chirimoya

**Comment by alexander-schranz** [comment] 2016-09-06 08:43
@Reyh currently you need to downgrade to `2.8.9` until symfony release a new version with there fix.

**Comment by Reyh** [comment] 2016-09-06 08:53
Yes i do it thx

**Comment by wachterjohannes** [comment] 2016-09-07 05:55
Symfony has released 2.8.11. I have tested it and i cannot reproduce this issue anymore. I will update the composer.lock and close this isse.

**Comment by wachterjohannes** [comment] 2016-09-07 06:00
https://github.com/sulu/sulu-standard/commit/c38d1269677a1034911295915be67eea7f35905f

**Closed by wachterjohannes** 2016-09-07 06:00 UTC
