### ISSUE TITLE
Google Analytics Tracking called at /admin

### ISSUE THREAD

**Issue by pjeroen** [sulu/sulu-standard#806] opened 2017-03-03 10:09 UTC
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.4.6.
| Browser Version | all (I guess)

#### Actual Behavior

Currently the Google Analytics Tracking Code is also embedded and fired at /admin (e.g. not at /admin/login). 

#### Expected Behavior

From our point of view, the tracking should not be embedded here.

#### Steps to Reproduce

For further information, please refer to Jens ;)

**Comment by danrot** [comment] 2017-03-13 12:48
This behavior is caused by the live preview... The analytic codes are also added when the preview is rendered. However, we don't add an Google Analytics Tracking Code, so this is probably implemented in your template. In the meantime it should be possible to check if the variable `request.analyticsKey` has a value of `UA-SULU-PREVIEW-KEY`. Couldn't find another way to check if the application is running in preview mode, so we should build something for that.

**Comment by alexander-schranz** [comment] 2017-03-13 12:57
To add the possibility to check for preview we should add a `preview` variable to the ParameterResolver: `https://github.com/sulu/sulu/blob/1.5.0/src/Sulu/Bundle/WebsiteBundle/Resolver/ParameterResolver.php`. 

But I think this will not fix the problem with the analyticsKey as it is added by responseListener. When we remove it we should mention that in the Upgrade.md as some projects maybe expect the the google analytics library is loaded and will maybe crash some Javascript code on the website.

@wachterjohannes can a service like the analytics response listeners be disabled for preview?

**Comment by wachterjohannes** [comment] 2017-03-13 14:23
in preview you could use `app.request.get('preview')` which is quite ugly but should work at the moment. we could also disable the listener when the kernel parameter `sulu.preview` is set.

**Comment by danrot** [comment] 2017-04-06 12:46
Fixed in #3295

**Closed by danrot** 2017-04-06 12:46 UTC
Labels: Bug
