### ISSUE TITLE
net::ERR_EMPTY_RESPONSE while website content loading on Admin backend.

### ISSUE THREAD

**Issue by diabolus** [sulu/sulu-standard#804] opened 2017-02-28 09:47 UTC
| Q | A
| --- | ---
| Bug? | Yes
| New Feature? | no
| Sulu Version | 1.2.1
| Browser Version | Google Chrome Version 58.0.3024.0 (Offizieller Build) canary (64-Bit)

#### Actual Behavior

For instance Sulu has 2 websites ( ex. `foo` website and `bar` website ). And During the user navigation, se_user_settings table saved the ColumnNavigationSelected key for `foo` website 
with a content id which belongs to `bar`.  And Every time that user try to open `foo` website content on admin page, regarding to invalid `fooColumnNavigationSelected` ajax call having an empty response and javascript execution throw an error and stops the page loading. 

#### Expected Behavior

Invalid content id's should be handled both controller and javascript side.

#### Steps to Reproduce

It is enough to change any ColumnNavigationSelected value on se_user_settings table for specific user and website. And When you click the 'content' submenu of the website with that user who has an invalid content id on ColumnNavigationSelected. Page generates a js error.
For instance;

/admin/api/nodes/b93bfc70-8aea-46f5-9f12-ec718f4…DE&fields=title,order&exclude-ghosts=false&exclude-shadows=false&tree=true net::ERR_EMPTY_RESPONSE

#### Possible Solutions

Content id validation is required for insertion of ColumnNavigationSelected to se_user_settings.
In case of invalid content id , controller should not response with empty body. And javascript should handle this error and load something like default content. 
Maybe it is also better to clean the invalid content id record on se_user_settings.

**Comment by danrot** [comment] 2017-03-13 06:48
> And During the user navigation, se_user_settings table saved the ColumnNavigationSelected key for foo website with a content id which belongs to bar.

The interesting question is how that happens. Can you provide some steps to reproduce for that?

**Comment by diabolus** [comment] 2017-03-22 08:37
Actually we noticed after it happened. We found it as a root of net::ERR_EMPTY_RESPONSE problem. Tried to investigate and reproduce it but do not have a clue how was it happened. ColumnNavigationSelected posting by javascript and i can occur while navigating admin site.

**Comment by danrot** [comment] 2017-03-22 11:34
Just to understand you correctly, there is a wrong value in the `se_user_settings` table, which is breaking the UI? And you have no idea how the wrong value landed in the database?

**Comment by diabolus** [comment] 2017-03-22 14:40
Exactly any idea. We experienced this in production environment. There is no option beyond the user navigation. There is no direct db access or something like that for users. And yes, It is breaking the UI after related Website clicked and XHR try to retrieve content from db with invalid content ID for that website.

**Comment by danrot** [comment] 2017-03-27 06:34
@diabolus I have just tested it, and cannot reproduce the error.

FYI: We always leave the UUID in the `se_user_settings`, also if the page gets deleted. So it is quite easily possible that the UUID listed there is not existing. JavaScript is then trying to retrieve the tree with the given UUID, but the server responds with a 404 error. Then JavaScript calls the root of the tree again. This looks like that in Chrome:

![image](https://cloud.githubusercontent.com/assets/405874/24343633/cc725bfc-12c7-11e7-8b90-b2a4fd496d44.png)

At least that's the behavior in version 1.4.11 (1.4 is the oldest release branch we are currently supporting).

However, I've googled your error message, and stumbled upon many different articles (e.g. [this one](https://www.wiknix.com/solved-err_empty_response-no-data-received/)) describing that this is not a server but a browser error. Maybe you can do some checks in this direction?

With the information being available I have to say that the issue is not reproducable, and I will close this issue. In case you are experiencing otherwise (also with later versions of Sulu) feel free to reopen the issue.

**Closed by danrot** 2017-03-27 06:34 UTC
Labels: Needs Information
