### ISSUE TITLE
Bug with ckeditor

### ISSUE THREAD

**Issue by toxicity1985** [sulu/sulu-standard#803] opened 2017-02-24 15:00 UTC
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | Specific version or SHA of a commit
| Browser Version | Browser name and version
![screen shot 2017-02-24 at 15 59 55](https://cloud.githubusercontent.com/assets/708329/23308116/5822a778-faaa-11e6-91ac-01f32665e9f2.png)

Hello, i install sulu on dev server and i begin to put all the content.
It works well until i have this error and i cannot edit the content anymore

aura_1: Syntax error, unrecognized expression: Etiam porta sem malesuada magna mollis euismod. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Donec sed odio dui. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.

Do you have an idea on how to resolve it ?

Best regards

**Comment by toxicity1985** [comment] 2017-02-28 07:32
Hey,

I'm debugging it and i found something. It's when we have " in the content description ...
Do you know where i can escape it ?

**Comment by wachterjohannes** [comment] 2017-02-28 09:03
could it be that you have saved the page when you where in "code"-mode of the ckeditor? and did you have raw text in database for this field?

If yes you could use the command `bin/console doctrine:phpcr:shell` to fix the content of the the property (wrap it with `<p></p>`

**Comment by danrot** [comment] 2017-04-04 06:35
I am pretty sure the solution from @wachterjohannes would work. Also, this is a duplicate of https://github.com/sulu/sulu/issues/3191, so I am closing it.

**Closed by danrot** 2017-04-04 06:35 UTC
