### ISSUE TITLE
adding images inside editor

### ISSUE THREAD

**Issue by iBasit** [sulu/sulu-standard#830] opened 2017-07-18 01:01 UTC
We can upload images and links to the images.  But cant we also add images inside the content with content editor? so the tag will be `<img..`.

Does sulu provide this functionality and if it does, how can I enable it? I dont want to add properties or blocks. just want to able to easily add images inside the content as any normal CMS / Blog system.

**Comment by danrot** [comment] 2017-07-24 06:54
That's a duplicate of #507. And as described there, I don't think that we are going to implement this, since this approach makes it impossible to properly implement a responsive design.

**Closed by danrot** 2017-07-24 06:54 UTC
Labels: Duplicate
