### ISSUE TITLE
The text for the internal link in the page list appears below the internal link icon

### ISSUE THREAD

**Issue by Elwe-Thingol** [sulu/sulu-standard#757] opened 2016-10-27 08:48 UTC
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.3.0 |
| Browser Version | The Bug appears in all browser except in Edge, even though the behaviour in Firefox is slightly different |
#### Actual Behavior

How does Sulu behave at the moment? 
The elements in the page list which represent internal links are displayed as follows:
The Text for the internal link is displayed below the internal link icon. If the internal links were hovered the then the text and the icon appear at the same height. After the hover the text of the internal link appears again below the internal link icon. In Firefox the internal link element is displayed correct after the hover.
#### Steps to Reproduce

1)  Open a page list with internal links
2) Hover the internal links

**Comment by danrot** [comment] 2016-11-10 10:46
I can't reproduce that issue, but maybe I simply don't know what to look out for... Can you maybe post a screenshot?

**Comment by Elwe-Thingol** [comment] 2016-11-10 15:05
![capture](https://cloud.githubusercontent.com/assets/17599335/20181702/773a44b6-a75f-11e6-9ce6-355343c7d842.PNG)
![2016-11-10 16_04_53-sulu - spitex bern - internet explorer](https://cloud.githubusercontent.com/assets/17599335/20181703/773bec8a-a75f-11e6-872a-9f4cb41f8285.png)

**Comment by danrot** [comment] 2016-11-14 07:10
Ok, I have checked the internal links content type. But I also can't reproduce the issue you are showing here. Have tested it with Sulu 1.3.0 and 1.4.1 on Mac OSX with Chrome, Firefox and Safari and with IE11 on Windows 8.1.

Closing the issue as non-reproducable, please add more information if available.

**Closed by danrot** 2016-11-14 07:10 UTC
