### ISSUE TITLE
Missing escaping of inputfields before processing in backend

### ISSUE THREAD

**Issue by rs2487** [sulu/sulu-standard#477] opened 2015-07-06 11:39 UTC
Please add escaping of formfield inputs before adding to database:

http://cl.ly/image/2c0r3L40192b/Bildschirmfoto%202015-07-06%20um%2013.38.51.png
http://cl.ly/image/0H09241j3s0c/Bildschirmfoto%202015-07-06%20um%2013.37.49.png

**Comment by danrot** [comment] 2015-10-08 05:41
@rs2487 Your links don't work anymore, can you please add images via github in the future? (just copy and paste an image in here should work)

For the record: IIRC this was only about the datagrid, right?

**Comment by rs2487** [comment] 2015-10-08 06:49
![bildschirmfoto 2015-10-08 um 08 41 55](https://cloud.githubusercontent.com/assets/1167787/10359401/8df550c6-6d98-11e5-9c6c-3fa8bec95d26.png)
![bildschirmfoto 2015-10-08 um 08 42 28](https://cloud.githubusercontent.com/assets/1167787/10359403/922ba83e-6d98-11e5-8bdc-e8bfdec7fe2d.png)

These were the two screenshots. They show the effects when input field (firstname and lastname in this case) are not escaped

LGR

**Comment by danrot** [comment] 2015-10-14 14:42
I am just asking myself where the best place for this would be. I would have thought about our husky-validation library. The library should also check a `data-validation-escaping` attribute, which means the library escapes the content of this field on a value of `true`.

However, I am not sure about the default value here. First I would have been going for `true`, because there is only one obvious exception, the rich text editor. But I am not sure how this handles the json values from other components like the media selection.

Another advantage of `false` as default value would be that it is not a BC break, since it is the current behavior.

@chirimoya @wachterjohannes WDYT?

**Comment by wachterjohannes** [comment] 2015-10-15 05:38
@danrot yes thats a quite good idea ... but i would solve this server side because it is a restful api and it should be handled there! how could we handle this on the serverside in a centric way?

**Comment by danrot** [comment] 2015-10-15 07:12
I don't think that this is a serverside task... Some fields may be escaped, and some not, I think the request has already to be correct.

**Comment by danrot** [comment] 2017-02-27 07:26
https://github.com/sulu/sulu/issues/3222 is a duplicate of this one, but I am still closing this one, since the other one is in the correct repository.

**Closed by danrot** 2017-02-27 07:26 UTC
Labels: Bug
